@startuml Context_View
actor Player
actor AI 
rectangle "Game" as Game
usecase "Start Game"
usecase "Place Ships"
usecase "Attack"
usecase "Receive Attack"
usecase "Check Win"

Player --> "Start Game"
Player --> "Place Ships"
Player --> "Attack"
Player --> Game
Game --> "Receive Attack"
Game --> "Check Win"
AI --> "Attack"
AI --> Game
@enduml