@startuml Development_View
package "Battleship Game" {
    [Game] --> [Player]
    [Game] --> [AI]
    [Player] --> [Board]
    [Player] <-- [AI]
    [Board] --> [Cell]
    [Board] --> [Ship]
}
@enduml