@startuml Physical_View
node "Local Machine" {
    node "Game" {
        component "UI"
        component "Game Logic"
        component "AI Logic"
    }
}

UI --> "Game Logic"
"Game Logic" --> "AI Logic"

@enduml